# Generated by Django 4.2.16 on 2024-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='venue',
            field=models.CharField(choices=[('venue1', 'Venue 1'), ('venue2', 'Venue 2'), ('venue3', 'Venue 3'), ('venue4', 'Venue 4'), ('venue5', 'Venue 5')], default=None, max_length=10),
        ),
    ]
