# Generated by Django 4.2.16 on 2024-09-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='panel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Healthcare Strategies in Climate-hit Regions'), (2, 'Empowering Women in Refugees Health Management'), (3, 'Innovation Solutions and Mental Health Support'), (4, 'Mental Health Support in Climate-Affected Regions')], default=1, verbose_name='Which panel would you like to attend'),
        ),
    ]
